### ISSUE TITLE
Key bindings?

### ISSUE THREAD

**Issue by iest** [Doi9t/SortBy#10]
Is there a way to use this tool with key bindings?

**Comment by Doi9t** [comment]
Hello,

I'm currently working on it, I will try to commit it asap.

Thanks

**Comment by Doi9t** [comment]
Hello, 

The chages are made, you can edit the key binding in file named Default.sublime-keymap located in the plugin directory:  (Via "Preferences" -> "Browse Packages..." -> SortBy (Folder) and edit the Default.sublime-keymap file.

**Comment by iest** [comment]
Amazing!! Thanks @Doi9t !

Keep up the great work :star2:
