### ISSUE TITLE
Sort by the last letter

### ISSUE THREAD

**Issue by wffger** [Doi9t/SortBy#11]
I have a tables list that I want to sort by the last letter. Because those tables are classified by suffix.

**Comment by tukusejssirs** [comment]
I’d suggest to add an option (argement) to all sort types to reverse all lines prior to sorting, sort them and reverse the lines back.

**Comment by Doi9t** [comment]
Hello, 

I know this is an old issue, but you can now use the regex sort, in the V2 of the plugin (ST3+).
