### ISSUE TITLE
Add option to ignore non-alphanumeric characters when sorting alphabetically

### ISSUE THREAD

**Issue by gilz688** [Doi9t/SortBy#13]
For example, I want the list to be sorted in the order below:
"overflow",
"overflow-x",
"-ms-overflow-x",
"overflow-y",
"-ms-overflow-y",

Instead of the following:
"-ms-overflow-x",
"-ms-overflow-y",
"overflow",
"overflow-x",
"overflow-y",

**Comment by madblobfish** [comment]
The suggested behaviour would sort like this (ignoring the non-alphanumeric `-`):
"-ms-overflow-x",
"-ms-overflow-y",
"overflow",
"overflow-x",
"overflow-y",

What you seem to want is ignoring prefixes (`-ms-` in your example).

This sorting behaviour can be faked by moving the prefix to the end of the line, sorting and then moving the prefix to the beginning of the line again.

**Comment by Doi9t** [comment]
Hello, 

I know this is old, but you can now use the regex sort, in the V2 of the plugin (ST3+).
