### ISSUE TITLE
How to short below values?

### ISSUE THREAD

**Issue by gsivaprabu** [Doi9t/SortBy#14]
"error_code_21": "Update mode.",
"error_code_211": "Server UnRechable",
"error_code_24": "OPERATION FAILED",
"error_code_349": "Memory  failed",
"error_code_4": "Error setting sal session",
"error_code_413": "SIZE EXCEED",
"error_code_414": "UPLOAD FAILED",
"error_code_50": "Error",
"error_code_500": "Error",

**I need like below**

"error_code_4": "Error setting sal session",
"error_code_21": "Update mode.",
"error_code_24": "OPERATION FAILED",
"error_code_50": "Error",
"error_code_211": "Server UnRechable",
"error_code_349": "Memory  failed",
"error_code_413": "SIZE EXCEED",
"error_code_414": "UPLOAD FAILED",
"error_code_500": "Error",

**Comment by Doi9t** [comment]
Hello,

To sort the the first text to be similar to the second, you can use the sort called: "Sortby: Integer" (It will use the first integer found in the string).

**Comment by gsivaprabu** [comment]
Thanks lot after installing i will check in edit menu sorting only, really awesome package,Thanks
