### ISSUE TITLE
Sort entire lines in selection, not only the selected characters only

### ISSUE THREAD

**Issue by tukusejssirs** [Doi9t/SortBy#23]
In Sublime Text, the default sort function sorts entire lines in selection, not only the selected characters. Could your plugin be configure to behave this same (either by default or using a setting) please? :wink:

**Comment by Doi9t** [comment]
Hello, 

This feature is now available in ST3+, on version 1.4.0 of the plugin.

The version will be available soon, as Package Control build & redeploy the version.

You can change the property "handle_selected_part_of_line_has_full_selected_line" to true to enable the feature.

And I've added a new shortcut to the property file.
![image](https://user-images.githubusercontent.com/1401670/124680483-83a3ac80-de94-11eb-9056-87d7f611778e.png)

Thanks for the suggestion!

**Comment by tukusejssirs** [comment]
Thanks, @Doi9t, for such quick implemention! :wink:

Just a quick question: should `handle_selected_part_of_line_has_full_selected_line` not actually be `handle_selected_part_of_line_as_full_selected_line`? Note the `has` → `as`.

**Comment by Doi9t** [comment]
Yup, there's a typo; I won't correct it, since it's already released. 

Thanks again!

**Comment by tukusejssirs** [comment]
@Doi9t, I have no idea how some plugins after clicking on `Plugin settings` (or actually they call it simply `Settings`) open two files side by side (i.e. in two groups) with default package settings on the left and user overrides on the right, but it is more user-friendly then opening the default package settings read only. Should I open a separate issues for this?

**Comment by Doi9t** [comment]
Hello, 

Sorry for the delay, I was really busy with other projects.

The fix & the typo are pushed; in the version 1.4.1 for ST3+

We have now both windows.
On the Left: The original file (read-only)
On the right: A new user file.
