### ISSUE TITLE
Sorting Now Deletes Lines (ST2)

### ISSUE THREAD

**Issue by reesespcres** [Doi9t/SortBy#24]
Possibly due to a recent update (?) but it seems that currently sorting by any method will remove all lines.

**Comment by Doi9t** [comment]
Hello,

I need more information.

What OS are you using?
Which version is installed (`Package Control: List Package`, and find `SortBy`)

Thanks!

**Comment by Doi9t** [comment]
I think I just found the issue, you rare probably using a version not designed for ST2 (> 1.2.0).

If it's the case, I made a mistake when setting the version on Package Control. :(

**Comment by reesespcres** [comment]
Hey @Doi9t,

I am currently using v1.4.1 so that would make sense. I hadn't changed anything locally that would affect the package and the I saw that there were some recent commits + Sublime packages auto updating. Thank you for taking a look!

**Comment by Doi9t** [comment]
I will fix the issue in Package Control, this can take more than one day to take effect; I highly suggest that you uninstall the plugin for the moment, and I will comment here when the change is applied (so you can reinstall).

You can also manually install the 1.2.0 if you want (https://github.com/Doi9t/SortBy/archive/refs/tags/st2-1.2.0.zip), if you need to use the plugin.
With the help of the documentation: https://github.com/Doi9t/SortBy#manual-installation

**Comment by reesespcres** [comment]
Will do, thanks @Doi9t!

**Comment by Doi9t** [comment]
Hello, 

FYI, the [PR is merged on Package Control](
https://github.com/wbond/package_control_channel/pull/8317#issuecomment-883673225); this issue should be fixed.

You should be able to reinstall and have the `1.2.0` as soon Package Control is deployed / updated correctly.
