### ISSUE TITLE
Sort by lenght of lines (Decending) removes indentation

### ISSUE THREAD

**Issue by aoliverwd** [Doi9t/SortBy#25]
Using version 2.0.0 on Sublime Text 4113
Mac M1 v11.4

Please below see before and after screen-grabs

![Screenshot 2021-07-20 at 08 27 23](https://user-images.githubusercontent.com/37518812/126279762-aee3f4b6-e738-4ccd-9cdc-652604da091d.png)
![Screenshot 2021-07-20 at 08 27 39](https://user-images.githubusercontent.com/37518812/126279768-1c98ffc1-5933-44c0-85ac-52bed9239bd2.png)

**Comment by Doi9t** [comment]
Hello,

I'm working on a fix (was stripping the line, for an unknown reason in the previous version); I did a lot of refactor in the 2.0.0 and introduced a bug.

Thanks for the issue!

**Comment by Doi9t** [comment]
The fix is pushed in 2.0.1, should be available soon.

**Comment by aoliverwd** [comment]
Amazing, thank you :)

**Comment by aoliverwd** [comment]
I can confirm it's working fine now. Thanks for such a quick turn around.
