### ISSUE TITLE
Sort by length of line + alphabetically

### ISSUE THREAD

**Issue by powelski** [Doi9t/SortBy#9]
Sometimes I need to sort lines by length, but keeping alphabetical order between the lines with identical length. It can be achieved by sorting alphabetically first and then by the length.

How about creating separate sort mode for this, so we could use just one step instead of two? This way of sorting is very useful if we want to keep the code tidy, for example I like to have PHP's `use` statements ordered this way.

**Comment by Doi9t** [comment]
The code is done (in an test file), I need to implement it into SortBy. 

Thanks for the suggestion !

**Comment by powelski** [comment]
Great, thank you!

**Comment by Doi9t** [comment]
Will put soon in the release (probably tomorrow, I need a break :) ), tested on sb3 build 3083 and SB2 build 2221

**Comment by Doi9t** [comment]
Hello,
The changes are pushed (You can activate the mode via the conf file SortBy.sublime-settings and enable "length_alphabetically_enabled")

**Comment by powelski** [comment]
Stupid question my friend, I don't quite see the config file for your package, plus there's no entry in the Preferences -> Package Settings dropdown.

**Comment by Doi9t** [comment]
For the moment, the only way to edit the config, is to edit the file manually (Via "Preferences" -> "Browse Packages..." -> SortBy (Folder) and edit the SortBy.sublime-settings file.

**Comment by powelski** [comment]
I don't even have this folder. I created SortBy folder and SortBy.sublime-settings. Then I put the following:
```
{
	"length_alphabetically_enabled": true
}
```
Unfortunetely, I still don't see the option.
